---

---
#project Machine Learning:
#loading packages
library(caret)
library(stringr)

#reading data:

training<- read.csv("Coursera/pml-training.csv")
testing<- read.csv("Coursera/pml-testing.csv")

#Cleaning data:
####Before an effective model can be built, it is necessary to remove features with poor out of sample predictive power from the data table. The user_name variable is removed in order to develop a model that can be extrapolated to new users. The X variable and the time dependent variables (raw_timestamp through num_window) are removed in order to blind the learning machines from any time dependent patterns that may not be present in a new sample.

training <-training[ , ! apply( training , 2 , function(x) any(is.na(x) )) ]

nzv<- nearZeroVar(training,saveMetrics=T)$nzv

training<- training[,which(nzv==FALSE)]

###Delete correlated viarables:
corrMatrix<- cor(training[,sapply(training, is.numeric)])

  highcorrvb<- findCorrelation(corrMatrix, cutoff = 0.9, verbose = TRUE)
  
  training<- training[,-highcorrvb]
  
  dim(training)

### Spliting data to train set and test set
####Due to the large sample size, 19622 points, it is possible to partition the training dataset further into a training set and a validation set. This allows the predictive capability of several models to be compared on the validation set before selecting the final model for use on the testing set. After applying the predictive model to the test set no more model tuning should take place to avoid overfitting.
intrain<- createDataPartition(training$classe,p=0.75,list=F)

train<- training[intrain,]

test<- training[-intrain,]

#train tree method:
trainrpart<- train(classe~.,method="rpart",data=train)

predrpart<- predict(trainrpart,test)

confusionMatrix(predrpart,test$classe)
##66%

#train Random Forest
trainrf<- train(classe~.,method="rf",data=train)

predrf<- predict(trainrf,test)

confusionMatrix(predrf,test$classe)
### the MMRS IS - 0
###100% Accuracy

#test-set
### now we are applying the model we built to the test-set
names<- names(training)

testing<- testing[,which(names %in% names(testing))]

predtest<- predict(trainrf,testing)

print(predtest)

B A B A A E D B A A B C B A E E A B B B
